### ISSUE TITLE
关于自定义动态域名后缀

### ISSUE THREAD

**Issue by hobbszhou** [elliotwutingfeng/go-fasttld#42]
这个库，支持自定义动态域名后缀加载吗?
![20220818-152402](https://user-images.githubusercontent.com/48123408/185335029-72cfbf54-f4de-42e3-bf60-a5515137e7a0.jpg)
![20220818-152357](https://user-images.githubusercontent.com/48123408/185335044-c6be1590-2d52-4708-80b2-60e856ad74b6.jpg)

**Comment by elliotwutingfeng** [comment]
Hi, 您可以使用 https://github.com/elliotwutingfeng/go-fasttld#specify-custom-public-suffix-list-file

```go
cacheFilePath := "/absolute/path/to/file.dat" // 把自定义后缀列表文件放在这里 (file.dat)
extractor, err := fasttld.New(fasttld.SuffixListParams{CacheFilePath: cacheFilePath})

url := "___"
res, _ := extractor.Extract(fasttld.URLParams{URL: url})
```
